global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'fastapi-app'
    static_configs:
      - targets: ['backend:8000'] 

  - job_name: 'drift-detector'
    static_configs:
      - targets: ['backend:9000']  
