name: TELE-MLOPS CI/CD 

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-and-deploy:
    name: Build → Push → Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Images
        run: |
          docker compose build

      - name: Tag and Push Images
        run: |
          docker tag anuragraj03/tele_mlops/custom-airflow:latest anuragraj03/tele_mlops:custom-airflow
          docker tag anuragraj03/tele_mlops/backend_process:latest anuragraj03/tele_mlops:backend_process
          docker tag anuragraj03/tele_mlops/frontend_run:latest anuragraj03/tele_mlops:frontend_run
          docker tag anuragraj03/tele_mlops/src_run:latest anuragraj03/tele_mlops:src_run
          docker tag anuragraj03/tele_mlops/llm_run:latest anuragraj03/tele_mlops:llm_run
          docker tag anuragraj03/tele_mlops/drift_detector_run:latest anuragraj03/tele_mlops:drift_detector_run
          

          docker push anuragraj03/tele_mlops:custom-airflow
          docker push anuragraj03/tele_mlops:backend_process
          docker push anuragraj03/tele_mlops:frontend_run
          docker push anuragraj03/tele_mlops:src_run
          docker push anuragraj03/tele_mlops:llm_run
          docker push anuragraj03/tele_mlops:drift_detector_run
          

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/tele_mlops_project

            echo "Pulling latest code..."
            git pull origin main

            echo "Cleaning old containers..."
            docker compose down

            echo "Pulling updated images..."
            docker pull anuragraj03/tele_mlops:custom-airflow
            docker pull anuragraj03/tele_mlops:backend_process
            docker pull anuragraj03/tele_mlops:frontend_run
            docker pull anuragraj03/tele_mlops:src_run
            docker pull anuragraj03/tele_mlops:llm_run
            docker pull anuragraj03/tele_mlops:drift_detector_run
   

            echo "Restarting containers..."
            docker compose up -d --remove-orphans